# Generated by Django 3.2.5 on 2021-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_jake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_back',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, unique=True, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='아이디'),
        ),
    ]
