# Generated by Django 3.2.5 on 2021-07-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomBaseUser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_year',
            field=models.DateField(max_length=10),
        ),
    ]
