# Generated by Django 3.2.5 on 2021-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210701_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
