# Generated by Django 3.2.5 on 2021-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210701_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_one',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_three',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_two',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
